### ISSUE TITLE
Dependency

### ISSUE THREAD

**Issue by tyoungNIO** [nio-blocks/accelerometer_chips#2]
The listed dependency says to "git install" instead of "pip install," and the install directory is Garrett's github. Perhaps we should use an alternate source/mirror?

**Comment by hansmosh** [comment]
@mattdodge Any reason why a PR hasn't been created for you branch yet?

**Comment by mattdodge** [comment]
I wasn't sure if the changes were working and needed Tom to validate but it looks like we should be good. I'll do a little bit more cleanup then submit the PR
